module.exports = {
    Ytdl: require('./Ytdl'),
    Igdl: require('./Igdl'),
    Wiki: require('./Wiki'),
    Toxic: require('./Toxic'),
    About: require('./About'),
    Menu: require('./Menu'),
    Donasi: require('./Donasi'),
    Nulis: require('./Nulis'),
    Lirik: require('./Lirik'),
    Cuaca: require('./Cuaca'),
    Quotes : require('./Quotes'),
    Brainly: require('./Brainly'),
    QrMaker: require('./QrMaker'),
    Gquotes: require('./Gquotes'),
    Jsholat: require('./Jsholat'),
    Primbon: require('./Primbon'),
    Translate: require('./Translate'),
    Animhentai: require('./Animhentai'),
    Downloader: require('./Downloader')
}
